// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbskdasieyuhvajopzbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpic2tkYXNpZXl1aHZham9wemJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MTMwMjgsImV4cCI6MjA2OTk4OTAyOH0.ZF328ky6HbN1UbBdKjmZwO2YGrmhW55A8ji5HHak3r0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});